# Generated by Django 3.0.6 on 2020-05-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('title', models.CharField(max_length=64)),
                ('repeat', models.CharField(max_length=8)),
                ('sound', models.CharField(max_length=255)),
            ],
        ),
    ]
